name: E2E test using Cypress
on:
  workflow_run:
    workflows: ["Format Project with Prettier"]
    types:
      - completed

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install-command: pnpm install
          record: true
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_URL: ${{ secrets.API_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
