name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: ${{ secrets.PACKAGE_NAME }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"refactor","section":"Code Refactors","hidden":false},{"type":"test","section":"Tests","hidden":false},{"type":"ci","section":"CI/CD","hidden":false},{"type":"revert","section":"Reverts","hidden":false},{"type":"style","section":"UI Updates","hidden":false},{"type":"build","section":"Build System","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false},{"type":"improvement","section":"Improvements","hidden":false}]'
